contentColumnType: string
fieldGroup: c073d458-3743-4e75-acc2-84b4e3337f8f
handle: twitterCard
instructions: 'Select the type of Twitter Card you want to use. Default will be ''summary'' if you make no selection.'
name: 'Twitter card'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Summary
        -
          - value
          - summary
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Summary Large Image'
        -
          - value
          - summary_large_image
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
