fieldLayouts:
  1c96ea41-5c14-40fa-93e5-60128dc476a7:
    tabs:
      -
        elements:
          -
            fieldUid: 93f4db62-4e9e-46d9-aa94-e561f7360bb7 # Head scripts
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ac5db5c-8d19-45b8-9f89-efed89b6f4c0
            warning: null
            width: 100
          -
            fieldUid: 98b26e91-5911-4ff0-a800-b711b72e563c # Body start scripts
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20ae92e5-dff1-4ab8-bf74-193048b06ac9
            warning: null
            width: 100
          -
            fieldUid: 7fc052f5-ca32-4ff6-aa15-69c9f63ac859 # Body end scripts
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc937fb6-2c39-46c2-9b60-572e31421259
            warning: null
            width: 100
        name: Content
        uid: c70342c6-1232-479f-b394-1e44e97846c5
handle: scripts
name: Scripts
sortOrder: 1
