defaultPlacement: end
enableVersioning: true
handle: home
name: 'Home pages'
propagationMethod: all
siteSettings:
  27fd5441-8230-4f21-8d4c-ae215e7076df: # Boilerplate
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: '{slug}'
structure:
  maxLevels: 1
  uid: 43fe3018-e149-4463-a93d-59d3106459fa
type: structure
